### PR TITLE
Difference Array & Fenwick Tree

### PR DESCRIPTION
**Pull request by aswal-ashutosh**

### CODE REVIEW

**Comment by rahulsain** [comment]
Please put these file in their respective folders.

**Comment by aswal-ashutosh** [comment]
I can put the **Difference array** in the Array folder. But what about **Fenwick Tree**? I can't find any suitable category for it.
Should I create a new folder named **Range Queries** or **Advance DS**?

**Comment by rahulsain** [comment]
it might go to tree section

**Comment by rahulsain** [comment]
I thinking adding label will do the work no need to merge any PRs

**Comment by aswal-ashutosh** [comment]
I have moved the **Difference Array** to the **Array** folder and created a new category for **Trees** as there wasn't any folder for it.

image
Merge is required as just adding the label is not working.

**Comment by rahulsain** [comment]
> I have moved the **Difference Array** to the **Array** folder and created a new category for **Trees** as there wasn't any folder for it.
> 
> image Merge is required as just adding the label is not working.

Reload two or three times, it will work

**Review by rahulsain — APPROVED** [review]

**Pull request closed without merging**
